### ISSUE TITLE
Legend colorbars just keep value of first scale

### ISSUE THREAD

**Issue by AlFontal** [benjaminleroy/cowpatch#17]
Hi! I came across your package while dealing with the headache of generating grids of figures with plotnine which aren't solvable with facets.

It works great for most cases, but I just realized that when using different colorbars (with different colormaps/breaks/values), only the one defined in the first figure is used and repeated for all plots. This might be useful when a unified legend is desired to be used, but that's not always the case.

A minimal example:

```python
import plotnine as p9
import cowpatch as cow
from plotnine.data import mtcars

a = (p9.ggplot(mtcars) 
    + p9.aes('wt', 'mpg', color='hp') 
    + p9.geom_point() 
    + p9.theme(figure_size=(1, .7))
)

b = (p9.ggplot(mtcars) 
    + p9.aes('wt', 'mpg', color='hp') 
    + p9.geom_point() 
    + p9.scale_color_continuous('inferno')
    + p9.theme(figure_size=(1, .7))

)

combi_plot = cow.patch(a, b) + cow.layout(ncol=2)
combi_plot.show(width=6, height=2)
```

<img width="812" alt="imagen" src="https://user-images.githubusercontent.com/10958332/200675938-fdd267c2-4428-449a-8ddc-ea681decde94.png">

I tried to take a look at the source code to see whether I could possibly fix the issue but I got pretty lost. Any ideas?

**Comment by benjaminleroy** [comment]
Hi @AlFontal. Thanks for the issue! I'll jump on this after work (PT). 

Before I dig into this, I wanted to mention that `cowpatch` doesn't actually mess with the underlying legends. If you're in a notebook, try something like `print(a); print(b)` to check that `plotnine` isn't accidently overriding anything.

**Comment by AlFontal** [comment]
Thanks for the super quick reply @benjaminleroy!

> I wanted to mention that cowpatch doesn't actually mess with the underlying legends

That's kind of what I got by looking at the source code, but there might be something under the hood that ends up overriding the subsequent legend patches? (I actually found the error when plotting 4 maps with 4 different colorscales, I wanted to use `cowpatch` instead of facets to be able to use different color maps).

The output of `print(a); print(b)` (so handled by `plotnine`) is correct (never mind the sizes that are now all messed up):

![imagen](https://user-images.githubusercontent.com/10958332/200686926-2590c702-f53a-4bd3-a70d-98f8bf829514.png)
![imagen](https://user-images.githubusercontent.com/10958332/200686944-3796b1dc-9159-4717-bf25-6e2689453068.png)

**Comment by benjaminleroy** [comment]
Interesting. And thanks in advance for the good example.

**Comment by benjaminleroy** [comment]
This is a really interesting problem. It looks like the SVG output created by `plotnine`/`matplotlib` uses `colorMat`, and some `linearGradient`s to describe the legend and if there are multiple definitions of the same value they can conflict.

If you need a hacky solution for the time being let me know.

**Comment by AlFontal** [comment]
Hmmm, can't be of much help right now, but I think it'd be definitely worthwile to have this eventually working in `cowpatch`.

I solved my specific use-case with `patchworklib` so far so no need for a quick hacky solution at this step, but I'll chime in if I get some time to look into the issue too.

Thanks!

**Comment by benjaminleroy** [comment]
Thanks. We're working on it.

**Comment by benjaminleroy** [comment]
Hi @AlFontal, sorry for the delay. You'll find v0.1.2 on pypi to have a bugfix for this problem. Thanks for finding the bug.

**Comment by AlFontal** [comment]
Awesome!

Just tested and it's working as expected.

Thanks for the great package 😄
